---
configRev: 1
longmynd:
    binpath: /home/pi/longmynd/longmynd
    mediapath: /home/pi/lmmedia
    statuspath: /home/pi/lmstatus
    tstimeout: 5000

bands:
    QO-100: &bandqo100
        lofreq: 9750000
        loside: LOW
    Direct: &banddirect
        lofreq: 0
        loside: HIGH

default:
    freq: 10491500
    sr:   1500
    band: *bandqo100
    pol:  NONE
    port: TOP

ir:
    repeatFirst: 200
    repeatDelay: 100
    repeatReset: 400
    libraryPath: /home/pi/RydeHandsets/definitions
    handsets:
        - virgin

gpio:
    repeatFirst: 200
    repeatDelay: 100
    rxGood: 4
    buttons:
        POWER:  16
        UP:     14
        DOWN:   27
        LEFT:   22
        RIGHT:  23
        SELECT: 24
        BACK:   25
        MENU:   5
        MUTE:   6

debug:
    autoplay: True
    disableHardwareCodec: True
